
medication = {"Abscess": "Oral regimens – For most patients with skin abscess, oral antibiotic therapy is sufficient. We suggest trimethoprim-sulfamethoxazole, doxycycline, or minocycline.",
"Acquired Capillary Haemangioma of Eyelid" : "Intralesional corticosteroid injection is the current treatment of choice. Other treatment methods employed include excisional biopsy and carbon dioxide laser. ",
"Acquired Immuno Deficiency Syndrome" : "It is treated with antiretroviral drugs, which stop the virus from replicating in the body.",
"Acute encephalitis syndrome" : "Intravenous aciclovir is a life-saving treatment in HSV encephalitis and has reduced mortality from above 70% to around 10–20%",
"Adult Inclusion Conjunctivitis": "Though there are some variations in the recommendation for antibiotics, accepted treatment options include doxycycline 100 mg twice daily, azithromycin 1000 mg single dose daily, tetracycline 100 mg 4 times daily for 7–10 days, or erythromycin 500 mg 4 times daily for seven days",
"Alcohol Abuse and Alcoholism" : "Acamprosate, disulfiram, and naltrexone are the most common drugs used to treat alcohol use disorder (AUD). They do not provide a cure for the disorder but are most effective in people who participate in a MAUD program.",
"Alopecia (hair loss)" : "In June 2022, the Food and Drug Administration (FDA) approved baricitinib for the treatment of severe alopecia areata in adults. In June 2023, the FDA approved ritlecitinib (marketed as LITFULO®),",
"Alzheimer" : "Galantamine, rivastigmine, and donepezil are cholinesterase inhibitors that are prescribed for mild to moderate Alzheimers symptoms.",
"Amaurosis Fugax" : "Most individuals require conservative treatment with anticoagulants (medications that inhibit the blood clotting process), such as aspirin and clopidogrel.",
"Amblyopia" : "An eyedrop of a medication called atropine (Isopto Atropine) can temporarily blur vision in the stronger eye. Usually prescribed for use on weekends or daily, use of the drops encourages your child to use the weaker eye, and offers an alternative to a patch.",
"Amoebiasis" : "Metronidazole is the drug of choice for symptomatic, invasive disease; paromomycin is the drug of choice for noninvasive disease. Because parasites persist in the intestines of 40-60% of patients treated with metronidazole,",
"Anaemia" : "Common medication options include supplements such as iron, vitamin B12, and folate. These are available by prescription or OTC.",
"Aniseikonia": "Management. Treatment varies based on the cause of aniseikonia. When it is due to anisometropia, treatment is with glasses, contact lenses, corneal refractive surgery, or lens-based refractive surgery.",
"Anisometropia": "Treatment for anisometropia can involve corrective lenses or surgery. Corrective lenses are only good for those with a difference between their eyes of 4D or less. Children under 12 and those with severe anisometropia are generally advised to use contacts, while others can often use glasses for correction.",
"Antepartum hemorrhage (Bleeding in late pregnancy)" : "The mainstays of management of massive haemorrhage are effective communication between clinical staff, resuscitation, monitoring and accurate diagnosis of the underlying cause. The bleeding will be arrested by delivery of the fetus. Severe bleeding: the mothers life should take priority.",
"Anthrax" : "The standard treatment for anthrax is an antibiotic such as ciprofloxacin (Cipro), doxycycline (Vibramycin) or levofloxacin.",
"Anxiety" : "Some of the anxiety medications with the fewest reported side effects and least risk of side effects include"
	"Most Benzodiazepines (Xanax, Valium)"
	"Bupropion (Wellbutrin)"
	"Citalopram (Celexa - SSRI)"
	"Paroxetine (Paxil - SSRI)",

"Appendicitis" : "The antibiotics used for appendicitis include:"
	"cefotetan (Cefotan)"
	"cefotaxime (Claforan)"
	"piperacillin and tazobactam (Zosyn)"
	"ampicillin and sulbactam (Unasyn)"
	"ceftriaxone (Rocephin)"
	"cefepime (Maxipime)"
	"gentamicin (Garamycin)"
	"meropenem (Merrem)",

"Arthritis" : "Nonsteroidal Anti-inflammatory Drugs (NSAIDs) NSAIDs relieve pain and inflammation by blocking hormone-like substances called prostaglandins. Naproxen (Aleve), aspirin and ibuprofen (Motrin, Advil) are available over the counter.",
"Asbestos":"related diseases - Common medications for asbestosis treatment include: Bronchodilators (inhalers) Typically prescribed for patients with asthma, inhalers help relax the airway muscles and may provide relief.",
"Aseptic meningitis" :  "Analgesics and anti-inflammatory medications may be recommended for pain and fever control.",
"Asthma": "Inhaled corticosteroids (beclomethasone, budesonide, ciclesonide, fluticasone, mometasone) are effective long-term asthma control medications.",
"Astigmatism": "For mild or moderate astigmatism, polycarbonate lenses are a great option.",
"Atrophy" : "Disuse (physiologic) atrophy can be treated with regular exercise and better nutrition. Your healthcare provider may recommend physical therapy or an exercise plan.",
"Autism" : "Risperidone (Risperdal) and Aripiprazole (Abilify) are the only drugs approved by the FDA for children with autism spectrum disorder.",
"Bad Breath" : "(Halitosis) Mouthwashes that contain antibacterial agents cetylpyridinium chloride (Cepacol), chlorhexidine (Peridex), or hydrogen peroxide are effective.",
"Bells Palsy" : "Recommended antivirals include valacyclovir (1 g three times per day for seven days) or acyclovir (400 mg five times per day for 10 days).",
"Beriberi" : "Beriberi is easily treated with thiamine supplements. Your doctor may prescribe a thiamine shot or pill.",
"Black Death" : "Most cures for the Plague dealt with balancing body humors, such as bloodletting. Other cures included gold, rose water, and theriac.",
"Bleeding Gums" : "Amoxicillin, Tetracycline, Metronidazol, Penicillin,... Depending on the individuals condition, Your doctor will guide you on the right dosage.",
"Blindness": "The two most widely used drugs at present are Lucentis (ranibizumab) and Avastin (bevacizumab). Both drugs are monoclonal antibodies that bind to all three forms of VEGF.",
"Botulism" : "Doctors treat botulism with a drug called an antitoxin, which prevents the toxin from causing any more harm. Antitoxin does not heal the damage the toxin has already done.",
"Brain Tumour": "Drugs Approved for Brain Tumors"
	"Afinitor (Everolimus)"
	"Afinitor Disperz (Everolimus)"
	"Alymsys (Bevacizumab)"
	"Avastin (Bevacizumab)"
	"Belzutifan."
	"Bevacizumab."
	"BiCNU (Carmustine)"
	"Carmustine.",
"Breast Cancer / Carcinoma" : "Palbociclib (Ibrance), ribociclib (Kisqali), and abemaciclib (Verzenio) are drugs that block proteins in the cell called cyclin-dependent kinases (CDKs), particularly CDK4 and CDK6.",
"Bronchitis" : "bronchitis can be effectively treated at home. Over-the-counter medicines like acetaminophen, ibuprofen, or aspirin can reduce fever.",
"Brucellosis" : "Two-drug regimen consisting of streptomycin and doxycycline (streptomycin for 2 to 3 weeks and doxycycline for 8 weeks) or gentamicin plus doxycycline (gentamicin for 5-7 days and doxycycline for 8 weeks) should be recommended",
"Bubonic plague" : "Antibiotics that treat bubonic plague include: Ciprofloxacin, levofloxacin and moxifloxacin.",
"Bunion": "Acetaminophen (Tylenol, others), ibuprofen (Advil, Motrin IB, others) or naproxen sodium (Aleve) can help you control the pain of a bunion.",
"Burns" : "Over-the-counter medications, such as ibuprofen (Advil, Motrin IB, others), naproxen sodium (Aleve) or acetaminophen (Tylenol, others), can help relieve pain.",
"Calculi" : "A kidney stone may be treated with shockwave lithotripsy, uteroscopy, percutaneous nephrolithomy or nephrolithotripsy.",
"Campylobacter infection" : "Most people with Campylobacter infection dont need antibiotics. They should drink plenty of fluids while diarrhea lasts. Some people with serious illness or at risk of serious illness might need antibiotics, such as azithromycin and ciprofloxacin.",
"Cancer" : "alkylating agents.""nitrosoureas." "antimetabolites.""anti-tumor antibiotics.""plant alkaloids.""corticosteroids.""miscellaneous drugs that do not fall into any of these categories",
"Candidiasis" : "For most adults, the initial recommended antifungal treatment is an echinocandin (caspofungin, micafungin, or anidulafungin) given through the vein (intravenous or IV).",
"Carbon monoxide poisoning" : "Guidance for Management of Confirmed or Suspected CO Poisoning. Administer 100% oxygen until the patient is symptom-free, usually about 4-5 hours. Serial neurologic exams should be performed",
"Carpal Tunnel Syndrome": "NSAIDs , such as ibuprofen (Advil, Motrin IB, others), may help relieve pain from carpal tunnel syndrome in the short term.",
"Cavities": "Fluoride treatments. If your cavity just started, a fluoride treatment may help restore your tooths enamel and can sometimes reverse a cavity in the very early stages.",
"Celiacs disease": "Steroids can ease severe symptoms of celiac disease while the intestine heals. Other drugs, such as azathioprine (Azasan, Imuran) or budesonide (Entocort EC, Uceris), ",
"Cerebral palsy" : "There is no cure for CP, but a childs quality of life can improve with: treatment that may involve medicine or surgery. therapy, including physical therapy, occupational therapy, and speech therapy.",
"Chagas disease": "The two drugs used to treat infection with T. cruzi are nifurtimox and benznidazole. Benznidazole is approved by FDA for use in children 2–12 years of age",
"Chalazion": "If the lesion is actively draining or associated with blepharoconjunctivitis, a topical antibiotic ointment can be applied for 1-2 weeks (erythromycin or bacitracin BID).",
"Chickenpox" : "if you or your child is at high risk of complications, your provider may suggest antiviral medicine to fight the virus, such as acyclovir (Zovirax, Sitavig).",
"Chikungunya Fever": "There is currently no vaccine to prevent or medicine to treat chikungunya. Rest, fluids, and over-the-counter pain medications may relieve some symptoms. Take medicine such as acetaminophen (Tylenol®) or paracetamol to reduce fever and pain.",
"Childhood Exotropia" : "Non-surgical treatment may include glasses and, in some instances, patching therapy may be recommended.",
"Chlamydia" : "If you are diagnosed with chlamydia, your doctor will prescribe oral antibiotics. A single dose of azithromycin or taking doxycycline twice daily for 7 to 14 days are the most common treatments",
"Cholera": "oxycycline is recommended as first-line treatment for adults (including pregnant women) and children. If resistance to doxycycline is documented, azithromycin and ciprofloxacin are alternative options.",
"Chorea": "Doctors prescribe deutetrabenazine (Austedo®) or tetrabenazine (Xenazine®) to control muscle movements of Huntingtons chorea. ",
"Chronic fatigue syndrome": "For example, the tricyclic amitriptyline is known to relieve many symptoms, including sleeplessness and low energy levels in CFS/ME.",
"Chronic obstructive pulmonary disease (COPD)" : "For most people with COPD, short-acting bronchodilator inhalers are the first treatment used. Bronchodilators are medicines that make breathing easier by relaxing and widening your airways.",
"Cleft Lip and Cleft Palate" : "Some drugs may cause cleft lip and cleft palate. Among them: anti-seizure/anticonvulsant drugs, acne drugs containing Accutane, and methotrexate, a drug commonly used for treating cancer, arthritis, and psoriasis.",
"Colitis" : "Aminosalicylates. Aminosalicylates, also known as 5-ASAs, are medicines that help to reduce inflammation.",
"Colorectal Cancer": "Some drugs commonly used for colorectal cancer include: 5-Fluorouracil (5-FU) Capecitabine (Xeloda), a pill that is changed into 5-FU once it gets to the tumor. Irinotecan (Camptosar) Oxaliplatin (Eloxatin) Trifluridine and tipiracil (Lonsurf), a combination drug in pill form.",
"Common cold" : "Pain relievers: Acetaminophen (Tylenol®) and NSAIDs such as ibuprofen (Advil®) may relieve headaches and fever.",
"Condyloma": "Podophyllotoxin 0.5% solution and 0.15% cream can be used to treat the fleshy papules. Podoxophyllin toxin is applied twice daily for three days, followed by a four-day break.",
"Congenital anomalies (birth defects)": "Some congenital disorders can be treated with surgical and non-surgical options, such as cleft lip and palate, clubfoot and hernias.",
"Congestive heart disease" : "Healthcare providers often prescribe ACE inhibitors and beta blockers as first-line treatments. These drugs are especially helpful for people who have a reduced ejection fraction. ",
"Corneal Abrasion" : "For uncomplicated abrasions, options include erythromycin 0.5% ophthalmic ointment, polymyxin B/trimethoprim (Polytrim) ophthalmic solution, and sulfacetamide 10% ophthalmic ointment or solution",
"Coronary Heart Disease": "Nitroglycerin. This medication treats angina, or chest pain, in people with coronary artery disease.",
"Coronavirus disease 2019 (COVID-19)": "For many people, over-the-counter medications, like Advil and Tylenol, are enough to reduce symptoms while the virus runs its course.",
"Cough" : "A common example is dextromethorphan (Robitussin, Delsym). Cough suppressants usually work better for a “dry” (non-productive) cough,",
"Crimean Congo": "haemorrhagic fever (CCHF) - The antiviral drug ribavirin has been used to treat CCHF infection with apparent benefit. Both oral and intravenous formulations seem to be effective. ",
"Dehydration" : "rehydrate the body by drinking plenty of fluids, such as water, diluted squash or diluted fruit juice.",
"Dementia": "The following are used to temporarily improve dementia symptoms. Cholinesterase inhibitors.",
"Dengue": "There is no specific medicine to treat dengue infection. If you think you may have dengue fever, you should use pain relievers with acetaminophen and avoid medicines with aspirin, which could worsen bleeding.",
"Diabetes Mellitus": "Metformin (Fortamet, Glumetza, others) is generally the first medicine prescribed for type 2 diabetes. It works mainly by lowering glucose production in the liver and improving the bodys sensitivity to insulin so it uses insulin more effectively. ",
"Diabetic Retinopathy" : "Three drugs are approved by the U.S. Food and Drug Administration (FDA) for treatment of diabetic macular edema — faricimab-svoa (Vabysmo), ranibizumab (Lucentis) and aflibercept (Eylea). ",
"Diarrhea" :  "you can treat your acute diarrhea with over-the-counter medicines such as loperamide link (Imodium) and bismuth subsalicylate link (Pepto-Bismol, Kaopectate).",
"Diphtheria" : "Using diphtheria antitoxin to stop the bacteria toxin from damaging the body. This treatment is very important for respiratory diphtheria infections, but it is rarely used for diphtheria skin infections",
"Down Syndrome" : "Therapy with multiple anticonvulsants such as carbamazepine, phenytoin, and valproic acid may be necessary for seizure control.",
"Dracunculiasis": "(guinea-worm disease) - There is no drug to treat Guinea worm disease and no vaccine to prevent Guinea worm infection.",
"Dysentery" : "Amebic dysentery is treated with metronidazole (Flagyl) or tinidazole (Tindamax).",
"Ear infection" : "Take over-the-counter (OTC) pain medication such as ibuprofen (Advil) or acetaminophen (Tylenol). Use OTC or prescription ear drops to relieve pain.",
"Early pregnancy loss" : "he most effective regimen for medication management of early pregnancy loss is mifepristone, 200 mg orally, followed 24 to 48 hours later by misoprostol, 800 mcg vaginally",
"Ebola" : "Inmazeb is a mixture of three monoclonal antibodies (atoltivimab, maftivimab, and odesivimab-ebgn). Ansuvimab-zykl (Ebanga) is a monoclonal antibody given as an injection.Oct 7, 2022",
"Eclampsia" : "Magnesium sulfate should be given to control convulsions and is the first-line treatment for eclamptic seizures. A loading dose of 4 to 6 grams should be given intravenously over 15 to 20 minutes.",
"Ectopic pregnancy" : "The most common drug used to treat ectopic pregnancy is methotrexate. This drug stops cells from growing, which ends the pregnancy.",
"Eczema" : "Corticosteroids are anti-inflammatory medications that can be very effective in relieving symptoms of eczema and dermatitis.",
"Endometriosis" : "Another highly effective way to treat endometriosis is to lower the natural estrogen levels altogether by giving an injectable medication, called leuprolide acetate (Lupron®). ",
"Epilepsy" : "valproic acid (Depakote): This is the standard broad-spectrum AED (treats all types of seizures) and no other AED is more effective for generalized seizure types. ",
"Fibroids" : "The one most commonly used is Lupron®. These drugs, given by injection, nasal spray, or implanted, can shrink your fibroids.",
"Fibromyalgia" : "Duloxetine (Cymbalta), milnacipran (Savella) and pregabalin (Lyrica) are FDA-approved to specifically treat fibromyalgia.",
"Food Poisoning": "In some cases, adults can take over-the-counter medicines such as loperamide link (Imodium) and bismuth subsalicylate link (Pepto-Bismol, Kaopectate) to treat diarrhea caused by food poisoning.",
"Frost Bite" : "Iloprost is sometimes used to treat severe frostbite. It works by widening the blood vessels that supply blood to the affected body part.",
"GERD" : "Prescription-strength proton pump inhibitors. These include esomeprazole (Nexium), lansoprazole (Prevacid), omeprazole (Prilosec), pantoprazole (Protonix), rabeprazole (Aciphex) and dexlansoprazole (Dexilant).",
"Gaming disorder" : "pharmacological drugs like atomoxetine, bupropion, and methylphenidate are used to treat the comorbidity of GD, such as attention deficit and hyperactivity disorder (ADHD) and depression, to relieve the severity of GD symptoms.",
"Gangrene" : "Gangrene thats caused by an infection can usually be treated with antibiotics, which can be given as tablets or injections.",
"Gastroenteritis" : "In some cases, adults can take over-the-counter medicines such as loperamide link (Imodium) and bismuth subsalicylate link (Pepto-Bismol, Kaopectate) to treat diarrhea caused by viral gastroenteritis.",
"Genital herpes": "Acyclovir, famciclovir, and valacyclovir appear equally effective for episodic treatment of genital herpes (466–470). *Acyclovir 400 mg orally 3 times/day is also effective, but are not recommended because of frequency of dosing.",
"Glaucoma": "Prostaglandins, like Xalatan (latanoprost), Travatan Z (travoprost), Zioptan (tafluprost), and Lumigan (bimatoprost)",
"Goitre" : "The drug levothyroxine (Levoxyl, Thyquidity, others) replaces T-4 and results in the pituitary gland releasing less TSH . ",
"Gonorrhea" : "CDC recommends a single dose of 500 mg of intramuscular ceftriaxone.",
"Guillain-BarrÃ© syndrome" : "The most commonly used treatment for Guillain-Barré syndrome is intravenous immunoglobulin (IVIG). When you have Guillain-Barré syndrome, the immune system (the bodys natural defences) produces harmful antibodies that attack the nerves.",
"Haemophilia" : "octocog alfa or a medicine called desmopressin. Desmopressin is a synthetic hormone. It works by stimulating the production of clotting factor VIII (8) and is usually given by injection.",
"Hand, Foot and Mouth Disease" : "Take over-the-counter medications to relieve fever and pain caused by mouth sores. These medications can include acetaminophen or ibuprofen.",
"Heat-Related Illnesses and Heat waves" : "Medications. These include antihistamines, diet pills, diuretics, sedatives, tranquilizers, stimulants, seizure medications (anticonvulsants), heart and blood pressure medications such as beta-blockers and vasoconstrictors,",
"Hepatitis": "Several antiviral medicines — including entecavir (Baraclude), tenofovir (Viread), lamivudine (Epivir), adefovir (Hepsera) and telbivudine — can help fight the virus and slow its ability to damage your liver. ",
"Hepatitis A": "There is no specific treatment for hepatitis A. Recovery from symptoms following infection may be slow and can take several weeks or months.",
"Hepatitis B": "Antiviral medications. Several antiviral medicines — including entecavir (Baraclude), tenofovir (Viread), lamivudine (Epivir), adefovir (Hepsera) and telbivudine",
"Hepatitis C" : "DAA tablets are the safest and most effective medicines for treating hepatitis C. Theyre highly effective at clearing the infection in more than 90% of people.",
"Hepatitis D": "Pegylated interferon alpha is the generally recommended treatment for hepatitis D virus infection.",
"Hepatitis E" : "Immunosuppressed people with chronic hepatitis E benefit from specific treatment using ribavirin, an antiviral drug.",
"Herpes Simplex" :"Antiviral agents for HSV infection include acyclovir, valacyclovir, and famciclovir. Metabolites of these nucleoside derivatives interfere with the synthesis of viral DNA by inhibiting viral DNA polymerase",
"High risk pregnancy" :  "eating a healthy diet, reducing exposure to toxins and harmful environmental factors, exercise, getting enough sleep and avoiding situations that create stress.",
"Human papillomavirus" : "Imiquimod. This topical medication helps eliminate warts by boosting the immune system. It is typically applied at home once a day, three times a week,",
"Hypermetropia" : "Eyeglasses. The lenses in eyeglasses provide a simple way to correct farsightedness. They do so by changing the way light focuses on your retina.",
"Hyperthyroidism" : "The main types used are carbimazole and propylthiouracil. Youll usually need to take the medicine for 12 to 18 months, and it may be a few months after you start taking it before you notice any benefit.",
"Hypothyroid": "An underactive thyroid (hypothyroidism) is usually treated by taking daily hormone replacement tablets called levothyroxine. Levothyroxine replaces the thyroxine hormone, which your thyroid does not make enough of.",
"Hypotonia" : "his is followed by treatment to improve symptoms and provide support, and may include physical, occupational, and speech-language therapies. Therapy for infants and young children may also include sensory stimulation programs.",
"Impetigo" : "Impetigo is treated with prescription mupirocin antibiotic ointment or cream applied directly to the sores two to three times a day for five to 10 days.",
"Inflammatory Bowel Disease" : "Doctors may prescribe 5-aminosalicylic acid medications, known as 5-ASAs, for people with mild to moderate IBD. 5-ASAs are more effective for ulcerative colitis,",
"Influenza" : "oseltamivir phosphate (available as a generic version or under the trade name Tamiflu®), zanamivir (trade name Relenza®) peramivir (trade name Rapivab®), and. baloxavir marboxil (trade name Xofluza®).",
"Insomnia" : "A sedative-hypnotic of the imidazopyridine class, zolpidem has a rapid onset and short duration of action. It is a good first choice for treatment of sleep-onset insomnia and produces no significant residual sedation in the morning.",
"Interstitial cystitis" : "Antihistamines, such as loratadine (Claritin, others), which may reduce urinary urgency and frequency and relieve other symptoms. Pentosan polysulfate sodium (Elmiron), which is approved by the Food and Drug Administration specifically for treating interstitial cystitis.",
"Iritis" : "Most often, treatment for iritis involves: Steroid eyedrops. Glucocorticoid medications, given as eyedrops, reduce inflammation. Dilating eyedrops.",
"Iron Deficiency Anemia" : "Ferrous sulfate is the mainstay treatment for treating patients with iron deficiency anemia. They should be continued for about 2 months after correction of the anemia and its etiologic cause in order to replenish body stores of iron.",
"Irritable bowel syndrome" : "Alosetron (Lotronex). Alosetron is designed to relax the colon and slow the movement of waste through the lower bowel",
"Japanese Encephalitis" : "An in vitro study showed that doxycycline and kanamycin administered in a dose-dependent manner decreased Japanese encephalitis viral RNA replication.",
"Jaundice" : "If itching is bothersome, taking cholestyramine by mouth may help. However, cholestyramine is ineffective when a bile duct is completely blocked.",
"Kala-azar/ Leishmaniasis" : "Liposomal amphotericin B alone, given as a single dose (currently recommended as the drug of choice by the Kala-Azar elimination programme of India) Liposomal amphotericin B in a single dose,",
"Kaposiâ€™s Sarcoma" : "Liposomal doxorubicin is used to treat Kaposi sarcoma. The liposomes build up in Kaposi sarcoma tissue more than in healthy tissue, and the doxorubicin is released slowly. ",
"Keratoconjunctivitis Sicca (Dry eye syndrome)" : "Topical cyclosporine 0.05% ophthalmic emulsion is effective FDA-approved treatment for dry eye disease.",
"Keratoconus" :  "progression of keratoconus is riboflavin 5´-phosphate ophthalmic solution. It is a photoenhancer indicated for use with ultraviolet (UV) A exposure in the procedure for corneal collagen cross-linking (CXL).",
"Kuru" : "There were no treatments that could control or cure kuru, other than discouraging the practice of cannibalism.",
"Laryngitis" : "Antibiotics. If laryngitis is caused by a bacterial infection, your healthcare provider may prescribe antibiotics. Antifungals. If the laryngitis is related to a candida or yeast infection, you may be given an antifungal.",
"Lead poisoning": "ethylenediaminetetraacetic acid (EDTA) chelation therapy.Health care providers treat adults with lead levels greater than 45 mcg/dL of blood and children who cant tolerate the drug used in conventional chelation therapy most commonly with a chemical called calcium disodium ethylenediaminetetraacetic acid (EDTA).",
"Legionellosis" : "Levofloxacin or azithromycin for 7–10 days is recommended in cases of moderate to severe Legionella pneumonia.",
"Leprosy" : "he currently recommended treatment regimen consists of three drugs: dapsone, rifampicin and clofazimine.",
"Leptospirosis" : "Leptospirosis is treated with antibiotics, such as doxycycline or penicillin, which should be given early in the course of the disease.",
"Leukemia" : "The following combinations of drugs have shown the best results in prolonging survival and are approved for first-line treatment."
	"Venetoclax (Venclexta®) and obinutuzumab (Gazyva®)"
	"Ibrutinib (Imbruvica®)"
	"High-dose methylprednisolone (HDMP) plus rituximab."
	"Ibrutinib and obinutuzumab."
	"Ofatumumab."
	"Chlorambucil.",
"Lice" : "Permethrin lotion 1% is approved by the FDA for the treatment of head lice. Permethrin is safe and effective when used as directed.",
"Lung cancer" : "Some of the more commonly used medications include cisplatin, carboplatin, pemetrexed, paclitaxel, docetaxel, gemcitabine, and vinorelbine. ",
"Lupus erythematosus" : "Immunosuppressants such as azathioprine, cyclophosphamide and methotrexate reduce lupus symptoms by lowering immune system activity.",
"Lyme disease" : "Antibiotics. The three first-line oral antibiotics for Lyme disease include doxycycline (Monodox, Doryx, Vibramycin, Oracea), amoxicillin (Amoxil), and cefuroxime (Ceftin, Zinacef). ",
"Lymphoma" : "Most often, the treatment is chemotherapy (chemo), usually with a regimen of 4 drugs known as CHOP (cyclophosphamide, doxorubicin, vincristine, and prednisone), plus the monoclonal antibody rituximab (Rituxan).",
"Mad cow disease" : "At present, treatment involves trying to keep the person as comfortable as possible and reducing symptoms with medicines.",
"Malaria" : "Artemether-lumefantrine (Coartem®) is the preferred follow-on treatment but adequate alternatives are atovaquone-proguanil (Malarone™), quinine plus doxycycline or clindamycin, or mefloquine.",
"Marburg fever" : "There is no specific treatment for Marburg virus disease. ",
"Mastitis" : "or simple mastitis without an abscess, your doctor will prescribe oral antibiotics. The most common ones are cephalexin (Keflex) and dicloxacillin (Dycill), but others are available.",
"Measles" : "There is no specific medical treatment for measles.",
"Melanoma" : "Both nivolumab and pembrolizumab have been shown to shrink melanoma for 25% to 45% of patients with unresectable (which means surgery is not an option) or stage IV melanoma, depending on when the treatment is given.",
"Middle East respiratory syndrome coronavirus (MERSâ€CoV)" : "Currently there is no cure for MERS. Treatment helps support your body while it fights the disease. This includes bed rest, pain medicines, oxygen, and IV fluids.",
"Migraine" : "Seven triptans have approval from the FDA and marketed for acute treatment of migraines. [7] They include sumatriptan, eletriptan, naratriptan, zolmitriptan, rizatriptan, frovatriptan, and almotriptan.",
"Mononucleosis" : "Theres no specific therapy available to treat infectious mononucleosis. Antibiotics dont work against viral infections such as mono",
"Mouth Breathing" : "Breathing retraining and proper tongue posture. Management of allergies or infections that may be causing nasal blockages.",
"Multiple myeloma" : "the immunomodulatory drugs currently used to treat multiple myeloma include the oral agents Revlimid (lenalidomide), Pomalyst (pomalidomide), and, less commonly, Thalomid (thalidomide). ",
"Multiple sclerosis" : "The following monoclonal antibodies may be prescribed as first-line treatments for MS: Ocrevus (ocrelizumab) is an infusion given every six months. Tysabri (natalizumab) is an infusion given every 28 days.",
"Mumps" : "There are currently no medicines to treat the mumps virus. The infection usually passes within a week or two.",
"Muscular dystrophy" : "Corticosteroids. Corticosteroids, such as prednisone, are powerful anti-inflammatory medications often prescribed for people with Duchenne muscular dystrophy or Becker muscular dystrophy.",
"Myasthenia gravis" : "The first medicine used for myasthenia gravis is usually a tablet called pyridostigmine, which helps electrical signals travel between the nerves and muscles.",
"Myelitis" : "Such drugs may include methylprednisolone or dexamethasone. These medications may also be given to reduce subsequent attacks of transverse myelitis in people with underlying disorders.",
"Myocardial Infarction (Heart Attack)" : "Emergency medical providers may give you aspirin immediately. Clot busters (thrombolytics or fibrinolytics). ",
"Myopia" : "Atropine. Atropine drops are commonly used to dilate the pupil of the eye, often as part of eye exams or before and after eye surgery.",
"Narcolepsy" : "Solriamfetol (Sunosi) and pitolisant (Wakix) are newer stimulants used for narcolepsy. Pitolisant also may be helpful for cataplexy. Some people need treatment with methylphenidate (Ritalin, Concerta, others) or amphetamines (Adderall XR 10, Dexedrine, others).",
"Nasal Polyps" : "Treatments might include: Nasal steroids. These nasal sprays include fluticasone (Flonase Allergy Relief, Xhance), budesonide (Rhinocort), mometasone (Nasonex 24hr Allergy), triamcinolone (Nasacort Allergy 24HR), beclomethasone (Beconase AQ, Qnasl) and ciclesonide (Omnaris, Zetonna). Steroids taken by mouth.",
"Nausea and Vomiting of Pregnancy and  Hyperemesis gravidarum" : "The American College of Obstetrics and Gynecology recommends that first-line treatment of nausea and vomiting of pregnancy should start with pyridoxine (vitamin B6) with or without doxylamine. ",
"Necrotizing Fasciitis" : "Possible regimens include a combination of penicillin G and an aminoglycoside (if renal function permits), as well as clindamycin (to cover streptococci, staphylococci, gram-negative bacilli, and anaerobes).",
"Neonatal Respiratory Disease Syndrome(NRDS)" : "Surfactant can be given into the babys lungs to replace what they do not have. This is given directly down the breathing tube that was placed in the windpipe.",
"Neoplasm" : "The most common treatments are surgery, chemotherapy, and radiation. Other options include targeted therapy, immunotherapy, laser, hormonal therapy, and others.",
"Neuralgia" : "The anti-convulsant drug most commonly prescribed for trigeminal neuralgia is carbamazepine (Tegretol), which can provide at least partial pain relief for up to 80 to 90 percent of patients.",
"Nipah virus infection" : "Theres no medication or vaccine to treat it. Managing symptoms is the only way to treat nipah virus.",
"Obesity" : "Orlistat, sold under the brand name Xenical among others, is a medication used to treat obesity. Its primary function is preventing the absorption of fats from the human diet by acting as a lipase inhibitor, thereby reducing caloric intake.",
"Obsessive Compulsive Disorder" : "Medications Clomipramine (Anafranil) for adults and children 10 years and older. Fluoxetine (Prozac) for adults and children 7 years and older. Fluvoxamine for adults and children 8 years and older. Paroxetine (Paxil, Pexeva) for adults only. Sertraline (Zoloft) for adults and children 6 years and older.",
"Oral Cancer" : "Cetuximab is a commonly prescribed targeted drug used to treat oral cancer. It targets a protein called epidermal growth factor receptor, which may be present in oral cancer tumors.",
"Orbital Dermoid" : "No medical care usually is required for an orbital dermoid. Inflammation that results from a ruptured dermoid cyst may be controlled with oral prednisone.",
"Osteoarthritis" : "Pills. NSAIDs are the most effective oral medicines for OA. They include ibuprofen (Motrin, Advil) naproxen (Aleve) and diclofenac (Voltaren, others). All work by blocking enzymes that cause pain and swelling.",
"Osteomyelitis" : "Oral antibiotics that have been proved to be effective include clindamycin, rifampin, trimethoprim-sulfamethoxazole, and fluoroquinolones. Clindamycin is given orally after initial intravenous (IV) treatment for 1-2 weeks and has excellent bioavailability.",
"Osteoporosis" : "Teriparatide (Bonsity, Forteo). This powerful drug is similar to parathyroid hormone and stimulates new bone growth. Its given by daily injection under the skin for up to two years.",
"Paratyphoid fever" : "The World Health Organization (WHO) currently recommends treatment with azithromycin, ciprofloxacin, or ceftriaxone due to widespread resistance to older, first‐line antimicrobials.",
"Parkinsons Disease" : "The main therapy for Parkinsons is levodopa. Nerve cells use levodopa to make dopamine to replenish the brains dwindling supply. ",
"Pelvic inflammatory disease" : "Cefoxitin, a second-generation cephalosporin, has better anaerobic coverage than ceftriaxone, and, in combination with probenecid and doxycycline, has been effective in short-term clinical response among women with PID.",
"Perennial Allergic Conjunctivitis" : "It can be treated with anti-allergy drops or antihistamines in eye drop form. Antihistamine tablets can also be helpful, and these will usually control hay fever also.",
"Pericarditis"  : "Pain relievers. Pericarditis pain can usually be treated with over-the-counter pain relievers, such as aspirin or ibuprofen (Advil, Motrin IB, others).",
"Peritonitis" : "Commonly used antibiotics for the treatment of peritonitis include beta-lactams (penicillins), carbapenems (beta-lactamase−resistant beta-lactams), cephalosporins (semi-synthetic beta-lactams), and quinolones (such as ciprofloxacin).",
"Pinguecula": "For patients with eye discomfort associated with a pinguecula, your doctor may prescribe artificial tears, gels or ointments to provide more lubrication to the eye.",
"Pneumonia" : "The first-line treatment for pneumonia in adults is macrolide antibiotics, like azithromycin or erythromycin. In children, the first-line treatment for bacterial pneumonia is typically amoxicillin.",
"Poliomyelitis" : "There are no specific medications to treat polio. If you have paralytic polio, youll receive physical therapy.",
"Polycystic ovary syndrome (PCOS)" : "A medicine called clomifene may be the first treatment recommended for women with PCOS who are trying to get pregnant. Clomifene encourages the monthly release of an egg from the ovaries (ovulation).",
"Porphyria" :  "Injections of hemin (Panhematin), a medicine that is a form of heme, to limit your bodys production of porphyrins. Receiving fluid that contains sugar, also called glucose, through a vein, or sugar taken by mouth, if able.",
"Post Menopausal Bleeding ": "Topical estrogen cream often resolves this kind of postmenopausal bleeding. Using lubrication during intercourse can help as well. If the lining of your uterus is super-thin, your ob-gyn might consider hormone therapy in the form of pills or an intrauterine device (IUD).",
"Post-herpetic neuralgia" : "Amitriptyline and duloxetine are the two main antidepressants prescribed for post-herpetic neuralgia. Youll usually be started on a low dose, which may be increased depending on the benefits and side effects. It may take a few weeks to feel the full effects.",
"Postpartum depression/ Perinatal depression" : "FDA has approved one medication, called brexanolone, specifically to treat severe postpartum depression. Administered in a hospital, this drug works to relieve depression by restoring the levels of these hormones.",
"Preeclampsia"  : "For emergency treatment in preeclampsia, IV hydralazine, labetalol and oral nifedipine can be used [1]. The ACOG Practice Bulletins also recommend that methyldopa and labetalol are appropriate first-line agents and beta-blockers and angiotensin-converting enzyme inhibitors are not recommended",
"Premenstrual syndrome" : "Selective serotonin reuptake inhibitors — Selective serotonin reuptake inhibitors (SSRIs) are a highly effective treatment for the symptoms of PMS and PMDD.",
"Presbyopia" : "Vuity (pilocarpine hydrochloride) and Qlosi (pilocarpine hydrochloride) are FDA-approved eye drops to treat presbyopia. Pilocarpine hydrochloride is a cholinergic muscarinic receptor agonist that works to improve near and intermediate visual acuity by contracting the iris sphincter muscle to constrict the pupil.",
"Preterm birth" : "Drugs called tocolytics (pronounced toh-coh-LIT-iks) can be given to many women with symptoms of preterm labor.",
"Progeria" : "Progeria treatment includes the use of a drug called lonafarnib (Zokinvy™). Originally developed to treat cancer, lonafarnib has been shown to improve many aspects of progeria.",
"Psoriasis" : "Corticosteroids. These drugs are the most frequently prescribed medications for treating mild to moderate psoriasis. They are available as oils, ointments, creams, lotions, gels, foams, sprays and shampoos.",
"Puerperal sepsis" : "Cephalosporin and Quinolones should be considered in managing puerperal sepsis in our facility but more importantly prevention of maternal sepsis is essential.",
"Pulmonary embolism ": "Anticoagulant Medication, They are often given immediately to people suspected of having pulmonary embolism. These medications, which may include rivaroxaban, heparin, or warfarin, slow the formation of blood clots.",
"Ques fever" : "Most people who are sick with Q fever will recover without antibiotic treatment. However, for people who develop Q fever disease, treatment with 2 weeks of doxycycline antibiotic is recommended.",
"Quinsy" : "Your healthcare provider will prescribe antibiotics, which may be given intravenously (through a vein) or taken in pill form. Common oral (by mouth) antibiotics include penicillin, amoxicillin, cephalosporin and clindamycin.",
"Rabies" : "Postexposure prophylaxis (PEP) consists of a dose of human rabies immune globulin (HRIG) and rabies vaccine given on the day of the rabies exposure, and then a dose of vaccine given again on days 3, 7, and 14.",
"Raynauds Phenomenon" : "Calcium channel blockers are the class of drugs most widely used for treatment of Raynaud syndrome—especially the dihydropyridines (eg, nifedipine, nicardipine), which are the most potent vasodilators.",
"Repetitive strain injury" : "Anti-inflammatory medicines, including both over-the-counter medications like NSAIDs (such as Ibuprofen) and prescription options like corticosteroid injections, can relieve overuse injury symptoms.",
"Rheumatic fever" : "Oral prophylaxis — Options for oral prophylaxis include penicillin V, macrolides, and sulfadiazine (table 3). The preferred oral agent in patients without penicillin allergy is penicillin V (250 mg twice daily)",
"Rheumatism" : "Methotrexate is usually the first medicine given for rheumatoid arthritis, often with another DMARD and a short course of steroids (corticosteroids) to relieve any pain.",
"Rickets" : "Most cases of rickets can be treated with vitamin D and calcium supplements. Follow your childs doctors directions as to dosage. Too much vitamin D can be harmful.",
"Rift Valley fever" : "There are no FDA-approved treatments for Rift Valley Fever (RVF). Since most cases of RVF are mild and self-limiting, a specific treatment for RVF has not been established.",
"Rocky Mountain spotted fever" : "Doxycycline is the treatment of choice for RMSF, and all other tickborne rickettsial diseases. Use of antibiotics other than doxycycline is associated with a higher risk of fatal outcome from RMSF. ",
"Rubella" : "There is no specific medicine to treat rubella or make the disease go away faster. In many cases, symptoms are mild.",
"SARS": "Low-dose corticosteroids, like prednisolone at 0.5–1.0 mg/kg/day, are usually used in infections and ARDS. On the other hand, pulse doses of methylprednisolone at 0.5–1.0 g/day have been widely used in SARS, especially when patients deteriorated clinically in the second week.",
"SIDS" : "Theres no treatment for SIDS . But your babys pediatrician or other health care professional can talk with you about any risks your baby may have.",
"Sarcoidosis": "The immunosuppressants most commonly prescribed for sarcoidosis include methotrexate, azathioprine, and leflunomide. Your doctor will discuss these medications with you and if they are recommended as part of a comprehensive treatment strategy.",
"Sarcoma": "Imatinib is a tyrosine kinase inhibitor, which targets and blocks proteins called kinases found on the surface of cancer cells. These proteins send signals to the cells control center, telling it to grow and divide. By blocking the signals, the medication causes the sarcoma cells to die.",
"Scabies" : "Permethrin kills the scabies mite and eggs. Permethrin is the drug of choice for the treatment of scabies. Topical permethrin should be administered every 2-3 days for 1-2 weeks to treat crusted scabies.",
"Scarlet fever" : "Scarlet fever is usually treated with a 10-day course of antibiotics. This is often in the form of penicillin or amoxicillin tablets, although liquid may be used for young children. For people who are allergic to penicillin, alternative antibiotics like erythromycin can be used instead.",
"Schizophrenia" : "Newer medications, called atypical antipsychotics, are also effective in relieving the symptoms of schizophrenia. These medications, including quetiapine, risperidone, and aripiprazole, are generally prescribed because they pose a lower risk of certain serious side effects than conventional antipsychotics.",
"Sciatica" : "Over-the-counter pain relievers such as acetaminophen, aspirin, or NSAIDs (such as ibuprofen [Advil, Motrin], ketoprofen, or naproxen [Aleve])",
"Scrapie" : "Unfortunately, there is no treatment for scrapie. Scrapie is no different than any other livestock disease.",
"Scrub Typhus" : "Scrub typhus should be treated with the antibiotic doxycycline. Doxycycline can be used in persons of any age. Antibiotics are most effective if given soon after symptoms begin.",
"Scurvy" : "Ascorbic acid (Ascor, Vita-C, C-Time, Ascocid, Fruit C, Acerola C 500, Chew-C) Ascorbic acid (vitamin C) administered orally or parenterally effectively cures infantile and adult scurvy. This vitamin is used by the body for collagen synthesis and tissue repair.",
"Sepsis": "ceftriaxone (Rocephin), piperacillin-tazobactam, cefepime (Maxipime), ceftazidime (Fortaz), vancomycin (Firvanq), ciprofloxacin (Cipro), and levofloxacin (Levaquin).",
"Sexually transmitted infections (STIs)" : "STDs/STIs caused by bacteria or parasites can be treated with antibiotics. These antibiotics are most often given by mouth (orally). However, sometimes they are injected or applied directly to the affected area.",
"Shaken Baby Syndrome" : "Theres no medication to treat shaken baby syndrome. In severe cases, surgery may be required to treat bleeding in the brain.",
"Shigellosis" : "The following antibiotics are used to treat Shigella dysentery: Beta-lactams: Ampicillin, amoxicillin, third-generation cephalosporins (ceﬁxime, ceftriaxone), and pivmecillinam (not available in the United States) Quinolones: Nalidixic acid, ciproﬂoxacin, norﬂoxacin, and oﬂoxacin.",
"Shin splints" : "People with shin splints may also safely take nonsteroidal anti-inflammatory drugs, such as aspirin or ibuprofen, to quell pain. It may also be useful to invest in inserts, kinesiology tape, compression socks, or a foam roller, says Dr. Carter.",
"Shingles" : "Shingles is often treated with an antiviral medicine. These medicines can reduce the severity and duration of your shingles symptoms. Acyclovir, famciclovir, or valacyclovir are commonly prescribed.",
"Sickle-cell anemia" : "FDA has granted accelerated approval for Oxbryta (voxelotor) tablets to treat sickle cell disease in pediatric patients aged four up to 11 years. FDA had previously granted accelerated approval for Oxbryta for patients aged 12 years and older with sickle cell disease.",
"Smallpox" : "Brincidofovir. In June 2021, the FDA approved brincidofovir (also referred to its brand name TEMBEXA) for treatment of smallpox. Brincidofovirs effectiveness against smallpox was established with in vitro studies using related orthopoxviruses as well as variola.",
"Stevens Johnson syndrome" : "Pain medication to reduce discomfort. Medication to reduce inflammation of the eyes and mucous membranes (topical steroids). Antibiotics to control infection, when needed. Other oral or injected (systemic) medications, such as corticosteroids and intravenous immune globulin.",
"Stomach ulcers" : "These drugs include the prescription and over-the-counter medications omeprazole (Prilosec), lansoprazole (Prevacid), rabeprazole (Aciphex), esomeprazole (Nexium) and pantoprazole (Protonix).",
"Strep throat" : "Penicillin and amoxicillin are common antibiotics healthcare providers use to treat strep throat. If youre allergic to penicillin, the provider can prescribe another antibiotic. A healthcare provider may give you an antibiotic shot, or they may prescribe an antibiotic in either pill or liquid form.",
"Stroke" : "The main treatment for an ischemic stroke is a medicine called tissue plasminogen activator (tPA). It breaks up the blood clots that block blood flow to your brain. A healthcare provider will inject tPA into a vein in your arm.",
"Sub-conjunctival Haemorrhage" : "Subconjunctival hemorrhage treatment usually isnt necessary. Artificial tears (eye drops) can help relieve eye irritation if it occurs. Most broken blood vessels heal within two weeks.",
"Syphilis" : "A single injection of long-acting Benzathine penicillin G can cure the early stages of syphilis. This includes primary, secondary, or early latent syphilis. CDC recommends three doses of long-acting Benzathine penicillin G at weekly intervals for late latent syphilis or latent syphilis of unknown duration.",
"Taeniasis" : "Taeniasis can be treated with single doses of praziquantel (10 mg/kg) or niclosamide (adults and children over 6 years: 2 g, children aged 2–6 years: 1 g).",
"Tay-Sachs disease" : "Presently there is no specific treatment for Tay-Sachs disease. Anticonvulsant medicine may initially control seizures. Other supportive treatment includes proper nutrition and hydration and techniques to keep the airway open.",
"Tennis elbow" : "Taking painkillers, such as paracetamol, and NSAIDs, such as ibuprofen, may help ease mild pain and inflammation caused by tennis elbow.",
"Tetanus" : "Metronidazole (500 mg intravenously [IV] every six to eight hours) is the preferred treatment for tetanus, but penicillin G (2 to 4 million units IV every four to six hours) is a safe and effective alternative [13].",
"Thalassaemia" : "Medicines called luspatercept (Reblozyl) and hydroxyurea may be prescribed by a healthcare provider to treat thalassemia. Luspatercept can lessen the number of blood transfusions needed for people with moderate to severe anemia as a result of thalassemia",
"Tinnitus" : "For some, treatment with low doses of anti-anxiety drugs -- such as Valium or antidepressants such as Elavil -- help reduce tinnitus. The use of a steroid placed into the middle ear along with an anti-anxiety medicine called alprazolam has been shown to be effective for some people.",
"Tonsillitis" : "For some, treatment with low doses of anti-anxiety drugs -- such as Valium or antidepressants such as Elavil -- help reduce tinnitus. The use of a steroid placed into the middle ear along with an anti-anxiety medicine called alprazolam has been shown to be effective for some people.",
"Toxic shock syndrome" : "The usually prescribed antibiotics are nafcillin, oxacillin, and first generation cephalosporin. Nafcillin or oxacillin (2 g q4h) is generally recommended. Vancomycin can be used in penicillin-allergic patients. These agents have been known to increase TSST-1 in culture possibly by cell lysis.",
"Trachoma" : "The antibiotic of choice for treating active trachoma is azithromycin. The dose for children is 20 mg/kg in a single dose; adults receive a single dose of 1 g. The second-line treatment is topical tetracycline eye ointment 1%. Topical tetracycline is applied to both eyes twice a day for 6 weeks.",
"Trichinosis" : "If your provider discovers that you have roundworm (trichinella) parasites early, albendazole (Albenza) or mebendazole (Emverm) can kill the worms and larvae in the small intestine. The drugs may cause nausea, vomiting, diarrhea and stomach pain during the treatment.",
"Trichomoniasis" : "Recommended first-line (metronidazole) and alternative treatment (tinidazole) for trichomoniasis are nitroimidazoles.",
"Tuberculosis" : "The most common treatment for active TB is isoniazid INH in combination with three other drugs—rifampin, pyrazinamide and ethambutol. You may begin to feel better only a few weeks after starting to take the drugs but treating TB takes much longer than other bacterial infections.",
"Tularemia" : "Antibiotics used to treat tularemia include streptomycin, gentamicin, doxycycline, and ciprofloxacin.",
"Turners Syndrome" : "Somatropin. The National Institute for Health and Care Excellence (NICE) has produced guidance about somatropin, the growth hormone sometimes used to treat Turner syndrome. Studies reviewed by NICE found somatropin increased height by around 5cm. A number of different types of somatropin are available.",
"Urticaria": "Antihistamines. They are the first line treatment for all patients with CU. Classic H1 antihistamines with sedation as a side effect include chlorpheniramine, hydroxyzine, and diphenhydramine.",
"Varicose Veins" : "sodium tetradecyl sulfate systemic Drug class: sclerosing agents For consumers: dosage, side effects For professionals",
"Vasovagal syncope" : "A drug called fludrocortisone acetate thats normally used to treat low blood pressure may be helpful in preventing vasovagal syncope. Selective serotonin reuptake inhibitors also may be used. Therapies. Your doctor may recommend ways to decrease the pooling of blood in your legs.",
"Vitamin B12 Deficiency" : "Youll usually take cyanocobalamin tablets every day to prevent or treat vitamin B12 deficiency. However, you may also need vitamin B12 injections at first to boost your levels. It may take a few weeks before your vitamin B12 levels and symptoms (such as extreme tiredness or lack of energy) start to improve.",
"Vitiligo" : "Ruxolitinib (Opzelura™) is the only medication approved by the U.S. Food and Drug Administration (FDA) to restore lost skin color in people who have vitiligo.",
"Warkany syndrome" : "In clinical practice, subjects born with this rare disorder are usually treated to manage and contrast the complications that arise through traditional neurorehabilitation treatment, which includes speech therapy treatment, neuromotor treatment, occupational therapy and psychomotor treatment [20].",
"Warts" : "Peeling medicines include salicylic acid (stronger than you can buy at the store), tretinoin, and glycolic acid. Bleomycin: The dermatologist may inject each wart with an anti-cancer medicine, bleomycin. The shots may hurt.",
"Yaws"  : "Either of 2 antibiotics – azithromycin or benzathine penicillin – may be used to treat yaws: Azithromycin (single oral dose) at 30 mg/kg (maximum 2 g) is the preferred treatment.",
"Yellow Fever" : "There is no medicine to treat or cure infection. To prevent getting sick from yellow fever, use insect repellent, wear long-sleeved shirts and long pants, and get vaccinated.",
"Zika virus disease" : "The best protection from Zika virus is preventing mosquito bites indoors and outdoors, especially from sunrise to sunset when mosquitos are most active. Such measures include: Use mosquito repellent in accordance with the instructions indicated on the product label. Wearing long-sleeved shirts and long trousers.",
"lactose intolerance" : "Over-the-counter tablets or drops containing the lactase enzyme (Lactaid, others) might help you digest dairy products. You can take tablets just before a meal or snack. Or the drops can be added to a carton of milk.",
"papilloedema": "If doctors rule out a life-threatening cause for your papilledema, they might recommend weight loss and a diuretic (water pill) called acetazolamide. This drug helps bring down the pressure inside your head by lessening the amount of fluid in your body as well as the amount of fluid your brain makes."
}


"""print (medication.get("Yellow Fever"))"""
